<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>TRY-CATCH</title>
</head>
<body>
    <script>
        try{
            console.log("Se agrega el c√≥digo a evaluar");
            noexiste
            console.log("segundo mensaje en el try");
        }catch(error){
            console.log("captura cualquier error surgido o lanzado en el try");
            console.log(error)
        }finally{
            console.log("El bloque finally se ejecutara siempre al final de un bloque try-catch");

        }


        try{
            let numero='y';
            if(isNaN(numero)){
              throw new Error("El caracter entroducido no es nu numero");
            }
            console.log(numero*numero)
        }catch(error){
            console.log(`Se produjo el siguiente error ${error}`);
        }
    </script>
</body>
</html>